#! /bin/sh

bspc monitor -d code web chat read

bspc config top_padding 16
bspc config border_width 1
bspc config window_gap   2

bspc config split_ratio        0.50
bspc config borderless_monocle true
bspc config gapless_monocle    true
bspc config focus_by_distance  true

bspc config normal_border_color "#332d29"
bspc config active_border_color "#817267"
bspc config focused_border_color "#504339"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

#~/scripts/dzenpanel &
